# Generated by Django 3.0.5 on 2020-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200413_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_fond',
            field=models.FileField(default=1, upload_to='image_fond/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
