# Generated by Django 3.0.5 on 2020-04-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_category_image_fond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='media',
            new_name='medias',
        ),
    ]
